In [1]:
using Pkg
using CSV
using DataFrames
using Distributions
using Random
using StatsBase

LoadError: ArgumentError: Package StatsBase not found in current path:
- Run `import Pkg; Pkg.add("StatsBase")` to install the StatsBase package.


In [2]:
Pkg.installed()

┌ Warning: Pkg.installed() is deprecated
└ @ Pkg C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\Pkg\src\Pkg.jl:570


Dict{String, VersionNumber} with 7 entries:
  "CSV"           => v"0.9.11"
  "IJulia"        => v"1.23.2"
  "Chain"         => v"0.4.10"
  "Plots"         => v"1.25.5"
  "Distributions" => v"0.25.37"
  "DataFrames"    => v"1.3.1"
  "StatsPlots"    => v"0.14.30"

In [27]:
##Zmienne
#Menu z cenami

menu = Dict("BigMac"=>20, "Drwal"=>30, "McNuggets"=>23, "McChicken" => 25, "Wege" => 18)

#Produkty i ich data waznosci
val = Dict("BigMac"=>20, "Drwal"=>20, "McNuggets"=>15, "McChicken" => 25, "Wege" => 15)

#Początkowy stan produktów
#start = Dict("BigMac"=>20, "Drwal"=>20, "McNuggets"=>20, "McChicken" => 20, "Wege" => 20)
start = [1, 2, 1, 1, 0]
unfulfilled = zeros(5)



5-element Vector{Float64}:
 0.0
 0.0
 0.0
 0.0
 0.0

In [4]:
##Rozkłady 
#Ilość samochodów na minutę tworzymy rozkład zeby uzyc sample w funkcji
cars = [1, 2, 3, 4, 5]
prob = [0.15, 0.25, 0.2, 0.2, 0.1]
w = Weights(prob)

5-element Weights{Float64, Float64, Vector{Float64}}:
 0.15
 0.25
 0.2
 0.2
 0.1

In [7]:
##Główna funkcja kroku
#jeden krok = jedna minuta

function OneStep()
    #wylosować z rozkładu samochdów na minutę ile samochdów przyjedzie w tym kroku
    cars_num = sample(cars, w)
    #wylosować ilość osób w kazdym samochodzie, 1 samochod = jedna zmienna?
    num_ppl = Dict(i => rand(1:cars_num) for i in 1:cars_num)
    # wylosować zamówienia dla kazdego samochodu, zapisujemy je jako data DataFrame
    #gdzie kolumny to produkty zamowione a rzedy to nr samochodu
    orders = DataFrame(BigMac = zeros(cars_num), Drwal = zeros(cars_num),
    McNuggets = zeros(cars_num), McChicken = zeros(cars_num), Wege = zeros(cars_num))
    
    #losujemy zamowienia dla kazdego samochodu
    for i in 1:nrow(orders)
        for j in 1:length(num_ppl)
            prod = rand(1:ncol(orders))
            orders[i, prod] += 1
        end
    end
    
    
    


LoadError: syntax: incomplete: "function" at In[7]:4 requires end

In [31]:
cars_num = sample(cars, w)
    #wylosować ilość osób w kazdym samochodzie, 1 samochod = jedna zmienna?
    num_ppl = Dict(i => rand(1:cars_num) for i in 1:cars_num)
    # wylosować zamówienia dla kazdego samochodu, zapisujemy je jako data DataFrame
    #gdzie kolumny to produkty zamowione a rzedy to nr samochodu
    orders = DataFrame(BigMac = zeros(cars_num), Drwal = zeros(cars_num),
    McNuggets = zeros(cars_num), McChicken = zeros(cars_num), Wege = zeros(cars_num))
    
    #losujemy zamowienia dla kazdego samochodu
    for i in 1:nrow(orders)
        for j in 1:length(num_ppl)
            prod = rand(1:ncol(orders))
            orders[i, prod] += 1
        end
    end

    sum_order = sum.(eachcol(orders))
    start -= sum_order
    end_inv = start

for i in 1:length(end_inv)
    if(end_inv[i] < 0)
        unfulfilled[i] += end_inv[i]
        end_inv[i] = 0
    end
end


        
    
    



In [34]:
end_inv

5-element Vector{Float64}:
 0.0
 0.0
 0.0
 0.0
 0.0

In [33]:
unfulfilled

5-element Vector{Float64}:
 -5.0
 -3.0
 -2.0
 -1.0
 -1.0